<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { config, models, tags as _tags } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';
	import XMark from '$lib/components/icons/XMark.svelte';

	const i18n = getContext('i18n');

	const dispatch = createEventDispatcher();

	export let message;
	export let show = false;

	const DEFAULT_LIKE_REASONS = [
		'accurate_information',
		'followed_instructions_perfectly',
		'showcased_creativity',
		'positive_attitude',
		'attention_to_detail',
		'thorough_explanation',
		'other'
	];
	const DEFAULT_DISLIKE_REASONS = [
		'dont_like_the_style',
		'too_verbose',
		'not_helpful',
		'not_factually_correct',
		'didnt_fully_follow_instructions',
		'refused_when_it_shouldnt_have',
		'being_lazy',
		'other'
	];

	// Reason label map for config-driven tags
	const REASON_LABELS: Record<string, string> = {
		accurate_information: 'Accurate information',
		followed_instructions_perfectly: 'Followed instructions perfectly',
		showcased_creativity: 'Showcased creativity',
		positive_attitude: 'Positive attitude',
		attention_to_detail: 'Attention to detail',
		thorough_explanation: 'Thorough explanation',
		dont_like_the_style: "Don't like the style",
		too_verbose: 'Too verbose',
		not_helpful: 'Not helpful',
		not_factually_correct: 'Not factually correct',
		didnt_fully_follow_instructions: "Didn't fully follow instructions",
		refused_when_it_shouldnt_have: "Refused when it shouldn't have",
		being_lazy: 'Being lazy',
		other: 'Other'
	};

	let tags = [];

	let reasons = [];
	let reasonLabels: Record<string, string> = {};
	let selectedReason = null;
	let comment = '';

	let detailedRating = null;
	let selectedModel = null;

	$: categoryTagsEnabled = $config?.features?.enable_feedback_category_tags ?? true;
	$: layer2Enabled = $config?.features?.enable_feedback_layer2 ?? true;
	$: layer3Enabled = $config?.features?.enable_feedback_layer3 ?? true;
	$: layer3Prompt = $config?.features?.feedback_layer3_prompt || '';

	$: {
		const configTags = $config?.features?.feedback_layer2_tags ?? [];
		if (configTags.length > 0) {
			// Use admin-configured tags (same for both thumbs up/down)
			reasons = configTags.map((t: { key: string; label: string }) => t.key);
			reasonLabels = configTags.reduce(
				(acc: Record<string, string>, t: { key: string; label: string }) => {
					acc[t.key] = t.label;
					return acc;
				},
				{}
			);
		} else {
			// Fallback to hardcoded defaults
			reasonLabels = REASON_LABELS;
			if (message?.annotation?.rating === 1) {
				reasons = DEFAULT_LIKE_REASONS;
			} else if (message?.annotation?.rating === -1) {
				reasons = DEFAULT_DISLIKE_REASONS;
			}
		}
	}

	$: if (message) {
		init();
	}

	const init = () => {
		if (!selectedReason) {
			selectedReason = message?.annotation?.reason ?? '';
		}

		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		tags = (message?.annotation?.tags ?? []).map((tag) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		// if (!selectedReason) {
		// 	toast.error($i18n.t('Please select a reason'));
		// 	return;
		// }

		dispatch('save', {
			reason: selectedReason,
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
	};
</script>

{#if message?.arena}
	<div class="text-xs font-medium pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
		})}
	</div>
{/if}

<div
	class=" my-2.5 rounded-xl px-4 py-3 border border-gray-100/30 dark:border-gray-850/30"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-medium">{$i18n.t('How would you rate this response?')}</div>

		<!-- <div class=" text-sm">{$i18n.t('Tell us more:')}</div> -->

		<button
			on:click={() => {
				show = false;
			}}
		>
			<XMark className={'size-4'} />
		</button>
	</div>

	<div class="w-full flex justify-center">
		<div class=" relative w-fit overflow-x-auto scrollbar-none">
			<div class="mt-1.5 w-fit flex gap-1 pb-2">
				<!-- 1-10 scale -->
				{#each Array.from({ length: 10 }).map((_, i) => i + 1) as rating}
					<button
						class="size-7 text-sm border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {detailedRating ===
						rating
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-full disabled:cursor-not-allowed disabled:text-gray-500 disabled:bg-white dark:disabled:bg-gray-900"
						on:click={() => {
							detailedRating = rating;
						}}
						disabled={message?.annotation?.rating === -1 ? rating > 5 : rating < 6}
					>
						{rating}
					</button>
				{/each}
			</div>

			<div class="sticky top-0 bottom-0 left-0 right-0 flex justify-between text-xs">
				<div>
					1 - {$i18n.t('Awful')}
				</div>

				<div>
					10 - {$i18n.t('Amazing')}
				</div>
			</div>
		</div>
	</div>

	{#if layer2Enabled}
		<div>
			{#if reasons.length > 0}
				<div class="text-sm mt-1.5 font-medium">{$i18n.t('Why?')}</div>

				<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
					{#each reasons as reason}
						<button
							class="px-3 py-0.5 border border-gray-100/30 dark:border-gray-850/30 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedReason ===
							reason
								? 'bg-gray-100 dark:bg-gray-800'
								: ''} transition rounded-xl"
							on:click={() => {
								selectedReason = reason;
							}}
						>
							{reasonLabels[reason] ? $i18n.t(reasonLabels[reason]) : reason}
						</button>
					{/each}
				</div>
			{/if}
		</div>
	{/if}

	{#if layer3Enabled}
		<div class="mt-2">
			<textarea
				bind:value={comment}
				class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl"
				placeholder={layer3Prompt || $i18n.t('Feel free to add specific details')}
				rows="3"
			/>
		</div>
	{/if}

	<div class="mt-2 gap-1.5 flex justify-between">
		{#if categoryTagsEnabled}
			<div class="flex items-end group">
				<Tags
					{tags}
					suggestionTags={$_tags ?? []}
					on:delete={(e) => {
						tags = tags.filter(
							(tag) =>
								tag.name.replaceAll(' ', '_').toLowerCase() !==
								e.detail.replaceAll(' ', '_').toLowerCase()
						);
					}}
					on:add={(e) => {
						tags = [...tags, { name: e.detail }];
					}}
				/>
			</div>
		{:else}
			<div></div>
		{/if}

		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-full"
			on:click={() => {
				saveHandler();
			}}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>
