"""Drive authorization pairs on fixtures owned exclusively by this pass.

RUN-TAG: owui-phase7b-authorization-and-model-passes

The seed map chooses the actual owner: most feature-gated rows belong to the
admin, integration rows to the ordinary caller, and exports to the disposable
seed user. Never accept parameters from fresh_surface or another pass. Keep
the second response in full, including refusal bodies, before the owner can
consume the resource. Unsuccessful owner controls are evidence gaps, not proof
of isolation. Corpus requests supplement the structural positive control.
"""

import json
import os
import re
from contextlib import contextmanager, nullcontext
from copy import deepcopy
from dataclasses import dataclass, field
from urllib.parse import quote
from uuid import uuid4

from hostile_corpus import fetch_payloads
from openapi_surface import writable_string_fields

from . import plane, seeds
from .authorization_inventory import admin_gated_operations
from .benign_requests import benign_request
from .client import AttackClient, login
from .identities import PASSWORD
from .pass_support import pass_run


# Violation kinds a [[shared]] declaration in the attack surface may allow for
# one route. An administrator operation that is not refused is never sharing.
SHAREABLE = frozenset({'owner-marker', 'resource-id', 'same-object', 'write'})


@dataclass
class Authorization:
    tally: plane.Seeding
    controls: dict = field(default_factory=dict)
    violations: list = field(default_factory=list)
    shared: dict = field(default_factory=dict)


def _shared(surface):
    """Route -> the violation kinds its [[shared]] declaration allows."""
    return {entry['route']: frozenset(entry['allow']) for entry in surface.get('shared', [])}


def _nothing_happened(answer):
    # A handler that reports its own no-op -- `false` from a delete, `null` from an
    # update that matched no row the caller owns -- wrote nothing.
    return answer.body.strip() in {'false', 'null'}


def _is_seedable(route, surface):
    """An operation whose id cannot be seeded is out of scope for an ownership check.

    seeds.parameter_for raises KeyError for a parameter the surface records as
    unseedable, and _owner_key reaches it before plane._target gets the chance to
    skip the route. Filter here instead, so those operations never enter the
    denominator: a route nobody can seed is not a route whose ownership went
    unchecked.
    """
    path = route.split(' ', 1)[1]
    for name in re.findall(r'\{([^}]+)\}', path):
        try:
            declaration = seeds.parameter_for(path, name, surface)
        except KeyError:
            return False
        if 'unseedable' in declaration:
            return False
    return True


def targets(spec=seeds.SPEC, *, surface=None):
    admins = set(admin_gated_operations(spec))
    routes = [
        route
        for route in plane.operations(spec)
        if ('{' in route or route in admins) and _is_seedable(route, surface or seeds.SURFACE)
    ]
    return routes, admins


def _owner_key(path, surface):
    entries = {entry['key']: entry for entry in surface['parameter']}
    declaration = seeds.parameter_for(path, re.findall(r'\{([^}]+)\}', path)[-1], surface)
    while 'same_as' in declaration:
        declaration = entries[declaration['same_as']]
    if declaration.get('seeded_by') == 'seed_export':
        return 'exporter'
    if declaration.get('actor') == 'admin' or declaration['key'] == 'task':
        return 'admin'
    return 'user'


@contextmanager
def own_fixtures(identities, *, spec=seeds.SPEC):
    # Pin a marker into every declarative seed as well as capturing the token
    # generated by procedural seeders. No suite fixture dictionary is accepted.
    marker = f'crossuser_{uuid4().hex}'
    surface = seeds._fill_token(deepcopy(seeds.SURFACE), marker)
    parameters = seeds.resolve_parameters(identities.user, admin=identities.admin, surface=surface, spec=spec)
    namespace = parameters['/api/v1/configs/namespace/{namespace}', 'namespace']
    markers = (marker, namespace.removeprefix('attack_'))
    exporter = None
    try:
        export_user = next(entry for entry in surface['parameter'] if entry['key'] == 'user')['body']
        exporter = login(export_user['email'], export_user['password'], base_url=identities.admin.base_url, role='user')
        yield parameters, markers, surface, {'admin': identities.admin, 'user': identities.user, 'exporter': exporter}
    finally:
        try:
            task = parameters.get(('/api/tasks/stop/{task_id}', 'task_id'))
            if task:
                response = identities.admin.request('POST', f'/api/tasks/stop/{quote(task, safe="")}')
                response.close()
        finally:
            if exporter:
                exporter.close()


@contextmanager
def _actor(admin, actor, destructive):
    if not destructive:
        yield actor
        return
    if actor.identity['role'] == 'admin':
        disposable = plane._throwaway(admin)
    else:
        email = f'attack-crossuser-{uuid4().hex}@example.com'
        response = admin.request(
            'POST',
            '/api/v1/auths/add',
            json={'email': email, 'password': PASSWORD, 'name': 'Attack authorization', 'role': 'user'},
        )
        disposable = AttackClient(admin.base_url)
        try:
            disposable.authenticate(response, email, role='user')
        except Exception:
            disposable.close()
            raise
        finally:
            response.close()
    try:
        yield disposable
    finally:
        disposable.close()


def _request(admin, actor, route, target, tally, kwargs):
    guard = (
        plane.preserve_configuration(
            admin,
            route=route,
            report=tally.config_findings.append,
            unverified=lambda reason: tally.config_unverified.setdefault(route, reason),
        )
        if route.split(' ', 1)[0] not in {'GET', 'HEAD', 'OPTIONS', 'TRACE'}
        else nullcontext()
    )
    with guard, _actor(admin, actor, route in seeds.DESTRUCTIVE) as client:
        response = client.request(route.split(' ', 1)[0], target, **deepcopy(kwargs))
        try:
            # The shared driver's Outcome truncates diagnostics; authorization
            # needs the complete original body, and an admin configuration guard
            # even when the actor is an ordinary user.
            entered = plane.record(route, response.status_code, response, pass_name='crossuser')
            return plane.Outcome(response.status_code, entered, response.text)
        finally:
            response.close()


def _object_ids(body):
    if isinstance(body, dict):
        for key, value in body.items():
            if (key == 'id' or key.endswith('_id')) and isinstance(value, str):
                yield value
            yield from _object_ids(value)
    elif isinstance(body, list):
        for value in body:
            yield from _object_ids(value)


def _json_or_text(body):
    try:
        return json.loads(body)
    except ValueError:
        return body


def _same_object(stranger, owner):
    body = _json_or_text(owner.body)
    return (
        200 <= stranger.status < 300
        and 200 <= owner.status < 300
        and bool(body)
        and body is not True
        and owner.body == stranger.body
    )


def _check(result, route, stranger, owner, markers, *, admin_only, control, resource_ids=()):
    reasons = []
    if stranger.timed_out or (owner is not None and owner.timed_out):
        # No response is not a refusal, a disclosure, or an accepted write.
        # Status 0 would read as "not refused" and invent an authorization
        # violation out of a slow route.
        return
    if any(marker in stranger.body for marker in markers):
        reasons.append(('owner-marker', 'seeded owner marker in second-account response (including refusals)'))
    if admin_only and stranger.status not in {401, 403}:
        reasons.append(('admin', f'administrator operation was not refused: HTTP {stranger.status}'))
    if 200 <= stranger.status < 300:
        disclosed = set(_object_ids(_json_or_text(stranger.body))) & set(resource_ids)
        if disclosed:
            reasons.append(('resource-id', 'second account received an object containing the seeded resource id'))
    if owner is not None:
        if control:
            result.controls[route] = owner.status
        if _same_object(stranger, owner):
            reasons.append(('same-object', 'second account received the same nonempty object as the owner'))
        write = route.split(' ', 1)[0] not in {'GET', 'HEAD', 'OPTIONS', 'TRACE'}
        if write and 200 <= stranger.status < 300 and not _nothing_happened(stranger):
            reasons.append(('write', 'second account accepted a write to the owner resource'))
    allowed = result.shared.get(route, frozenset())
    for kind, reason in reasons:
        if kind in allowed:
            continue
        item = {'route': route, 'reason': reason, 'status': stranger.status, 'body': stranger.body[:2000]}
        result.violations.append(item)
        result.tally.body_failures.append(item)


def _benign(route, parameters, spec):
    """The schema's benign request, carrying the ids [[field]] declares for the route.

    Without them a route that needs a real id in a request field answers 404 to
    the owner too, and an owner control that fails proves nothing about isolation.
    """
    request = benign_request(route, parameters, spec)
    declared = plane._declared(parameters, route)
    if declared.get('json'):
        request['json'] = plane._hold_declared(request.get('json'), (), declared['json'])[0]
    if declared.get('params'):
        request['params'] = {**request.get('params', {}), **declared['params']}
    return request


def _requests(route, parameters, spec, fields, payloads, full):
    yield True, _benign(route, parameters, spec)
    names = fields.get(route, [])
    if names:
        for batch in plane._payload_batches(route, names, payloads, full=full):
            yield False, {**benign_request(route, parameters, spec), 'json': plane._body_for(names, batch)}


def drive_crossuser(identities, *, spec=seeds.SPEC, payloads=None, full=None):
    routes, admins = targets(spec)
    payloads = tuple(fetch_payloads() if payloads is None else payloads)
    full = os.getenv('ATTACK_FULL_CORPUS') == '1' if full is None else full
    fields = writable_string_fields(spec)
    with own_fixtures(identities, spec=spec) as (parameters, markers, surface, owners):
        with pass_run('crossuser', routes, identities.admin) as tally:
            result = Authorization(tally, shared=_shared(surface))
            # Delete children before parents within the shared removal group.
            ordered = sorted(
                routes,
                key=lambda r: (plane._read_before_destroy(r)[0], -r.count('/') if r.startswith('DELETE ') else 0, r),
            )
            for route in ordered:
                target = plane._target(route, parameters, tally)
                if target is None:
                    continue
                path = route.split(' ', 1)[1]
                owner = owners[_owner_key(path, surface)] if '{' in path else None
                resource_ids = [parameters[path, name] for name in re.findall(r'\{([^}]+)\}', path)]
                for control, kwargs in _requests(route, parameters, spec, fields, payloads, full):
                    stranger = _request(identities.admin, identities.intruder, route, target, tally, kwargs)
                    positive = _request(identities.admin, owner, route, target, tally, kwargs) if owner else None
                    _check(
                        result,
                        route,
                        stranger,
                        positive,
                        markers,
                        admin_only=route in admins,
                        control=control,
                        resource_ids=resource_ids,
                    )
                plane.flush_hits()
    return result
